USE AKSHAY;

CREATE TABLE INFORMATION(
	ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    GPA DECIMAL(5,2)
);

ALTER TABLE INFORMATION ADD DEPARTMENT VARCHAR(20);
 DESCRIBE INFORMATION;
-- ALTER TABLE INFORMATION DROP DEPARTMENT;
 
INSERT INTO INFORMATION VALUES(1,"AKSHAY",888.88,"CSE");


