USE EMPLOYEE;
CREATE TABLE EMPLOYEE_DETAILS(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    AGE INT,
    SALARY INT
);
ALTER TABLE EMPLOYEE_DETAILS ADD JOB_DESCRIPTION VARCHAR(20);
DESC EMPLOYEE_DETAILS;
INSERT INTO EMPLOYEE_DETAILS VALUES(1,"AKSHAY",18,200000,"ML ENGINEER");
SELECT * FROM EMPLOYEE_DETAILS;
INSERT INTO EMPLOYEE_DETAILS VALUES
	(1,"AKSHAY",18,200000,"ML ENGINEER"),
	(2,"PIRANAV",29,20000,"AI ENGINEER"),
    (3,"SRI",18,200000,"CA"),
    (4,"LATHA",18,100000,"TEACHER"),
    (1,"AKSHAY",18,200000,"DATA SCIENTIST");
SELECT EMP_ID,EMP_NAME FROM  EMPLOYEE_DETAILS;
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_NAME="AKSHAY";
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_NAME<>"AKSHAY"; -- NOT EQUAL TO
SELECT * FROM EMPLOYEE_DETAILS WHERE AGE<=18;
SELECT * FROM EMPLOYEE_DETAILS WHERE AGE>=18;
SELECT * FROM EMPLOYEE_DETAILS WHERE SALARY BETWEEN 100000 AND 2000000;
SELECT * FROM EMPLOYEE_DETAILS WHERE SALARY IN (10000,20000) ;
SELECT * FROM EMPLOYEE_DETAILS WHERE SALARY NOT IN (10000,20000) ;

SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_NAME LIKE 'Z%';
SELECT * FROM EMPLOYEE_DETAILS WHERE EMP_NAME LIKE '__S%';

-- UPDATE EMPLOYEE_DETAILS SET AGE=18 WHERE AGE=29;
-- DELETE FROM EMPLOYEE_DETAILS WHERE ID=2;

SELECT DISTINCT * FROM EMPLOYEE_DETAILS;
SELECT * FROM EMPLOYEE_DETAILS ORDER BY SALARY,AGE DESC;
/*
SELECT * FROM EMPLOYEE_DETAILS ORDER BY ( CASE EMP_ID 
WHEN EMP_ID=3 THEN 1
WHEN EMP_ID=1 THEN 2
ELSE 100 END
);
*/
-- FUNCTIONS
SELECT COUNT(*) FROM EMPLOYEE_DETAILS;
SELECT COUNT(*) FROM EMPLOYEE_DETAILS WHERE AGE =18;
SELECT AVG(SALARY) FROM EMPLOYEE_DETAILS ;
SELECT MAX(SALARY) FROM EMPLOYEE_DETAILS ;
SELECT MIN(SALARY) FROM EMPLOYEE_DETAILS ;
SELECT SUM(SALARY) FROM EMPLOYEE_DETAILS ;
-- SELECT UCASE(EMP_NAME)  FROM EMPLOYEE_DETAILS;
SELECT UCASE(EMP_NAME) NAME FROM EMPLOYEE_DETAILS;
-- STRING
SELECT CONCAT('RS.',SALARY)  FROM EMPLOYEE_DETAILS;
SELECT CONCAT('RS.',FORMAT(SALARY,0)) SALARY  FROM EMPLOYEE_DETAILS;
-- DATE AND DATE FUNCTIONS IN SQL
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN HIRED_DATE DATE;
SELECT LEFT(EMP_NAME,3) JOB_NAME FROM EMPLOYEE_DETAILS;
SELECT RIGHT(EMP_NAME,3) JOB_NAME FROM EMPLOYEE_DETAILS;
UPDATE EMPLOYEE_DETAILS SET HIRED_DATE='2003/12/18';
UPDATE EMPLOYEE_DETAILS SET HIRED_DATE ='2018/12/13' WHERE JOB_DESCRIPTION = "CA";
SELECT NOW();
SELECT CURDATE();
SELECT DATE(NOW());
SELECT DATE_FORMAT(CURDATE(),"%D/%M%Y") AS DATE;
SELECT DATEDIFF(CURDATE(),"2003/12/12") AS DATE
 SELECT DATE_ADD(CURDATE(),INTERVAL 1 YEAR) AS "AFTER ONE YEAR";
-- GROUP BY & HAVING
SELECT JOB_DESCRIPTION,AVG(SALARY) AS SALARY FROM EMPLOYEE_DETAILS GROUP BY JOB_DESCRIPTION;
SELECT JOB_DESCRIPTION,COUNT(EMP_NAME) FROM EMPLOYEE_DETAILS GROUP BY JOB_DESCRIPTION;
SELECT JOB_DESCRIPTION,COUNT(EMP_NAME) FROM EMPLOYEE_DETAILS WHERE SALARY >20000 GROUP BY JOB_DESCRIPTION HAVING COUNT(EMP_NAME)>2;


 