-- USING CONSTRAINTS DIRECTLY

USE EMPLOYEE;
CREATE TABLE INTERMEDIATE
(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(20) NOT NULL,
    SALARY INT,
    JOB_DESCRIPTION VARCHAR(20) DEFAULT 'ONUMILLA',
    PAN VARCHAR(20) UNIQUE,
    CHECK (SALARY>200000)
); 
INSERT INTO INTERMEDIATE(EMP_NAME) VALUES("AKSHAY")
SELECT * FROM INTERMEDIATE;
DROP TABLE INTERMEDIATE;