USE EMPLOYEE;
CREATE TABLE PRACTICE
(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
	EMP_NAME VARCHAR(20),
	AGE INT,
    SALARY BIGINT,
    BRANCH_ID VARCHAR(20)
);
DROP TABLE PRACTICE;
CREATE TABLE PRACTICE1
(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
	EMP_NAME VARCHAR(20),
	AGE INT,
    SALARY BIGINT,
    BRANCH_ID VARCHAR(20),
    CONSTRAINT  FOREIGN KEY (BRANCH_ID) REFERENCES PRACTICE(BRANCH_ID)
);
DESCRIBE PRACTICE;

-- INDEX
CREATE TABLE EMPLOYEE
(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(20) NOT NULL,
    SALARY INT,
    JOB_DESCRIPTION VARCHAR(20) DEFAULT 'ONUMILLA',
    PAN VARCHAR(20) UNIQUE,
    CHECK (SALARY>200000)
); 
SHOW INDEX FROM EMPLOYEE;

CREATE INDEX NAME_INDEX ON EMPLOYEE(EMP_NAME);
-- ALTER TABLE EMPLOYEE ADD INDEX (EMP_NAME);

ALTER TABLE EMPLOYEE DROP INDEX NAME_INDEX;

DROP TABLE EMPLOYEE;




