USE PRACTICE;

CREATE TABLE BRANCH
(
	BRANCH_ID INT PRIMARY KEY,
    BRANCH_ADDRESS VARCHAR(20)
);


CREATE TABLE EMPLOYEE_DETAILS
(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(20),
    JOB_DESCRIPTION VARCHAR(20),
    BRANCH_ID INT,
    CONSTRAINT FK_BRANCHID FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

INSERT INTO BRANCH VALUES
	(1,"VIRUDHUNAGAR"),
    (2,"MADURAI"),
    (3,"CHENNAI"),
    (4,"POLLACHI"),
    (5,"COIMBATORE");
    
INSERT INTO EMPLOYEE_DETAILS VALUES
	(1,"AKSHAY","ML ENGINEER",1),
	(2,"PIRANAV","ML ENGINEER",2),
	(3,"LATHA","TEACHER",1),
	(4,"BEEMA","BOARD DIRECTOR",3),
	(5,"AKSHAY PIRANAV B","CEO",4),
	(6,"SRI","CA",4),
	(7,"SRINITHI","CA",4),
	(8,"VANAJA","COUNSELLOR",5),
	(9,"DHANUSH","BUSINESS MAN",5);
  
SELECT EMPLOYEE_DETAILS.EMP_ID,EMPLOYEE_DETAILS.EMP_NAME,EMPLOYEE_DETAILS.JOB_DESCRIPTION,BRANCH.BRANCH_ID
FROM EMPLOYEE_DETAILS INNER JOIN BRANCH WHERE EMPLOYEE_DETAILS.BRANCH_ID=BRANCH.BRANCH_ID;

-- BOTH INNER JOIN AND JOIN ARE SAME BUT ORDER CHANGES

SELECT B.BRANCH_ADDRESS,COUNT(E.EMP_ID) NO_OF_EMPLOYEE
FROM BRANCH AS B
JOIN EMPLOYEE_DETAILS AS E
ON B.BRANCH_ID =E.BRANCH_ID
GROUP BY E.BRANCH_ID;

SELECT B.BRANCH_ADDRESS,COUNT(E.EMP_ID)  NO_OF_EMPLOYEE
FROM EMPLOYEE_DETAILS AS E
 JOIN BRANCH AS B
ON B.BRANCH_ID =E.BRANCH_ID
GROUP BY E.EMP_ID;








